name: Nightly Script

on:
  schedule:
    # 00:30 UTC Monday
    - cron: '30 0 * * 1'
  workflow_dispatch: 

jobs:
  run-and-save:
    runs-on: ubuntu-latest

    env:
      AICORE_AUTH_URL: ${{ secrets.AICORE_AUTH_URL }}
      AICORE_CLIENT_ID: ${{ secrets.AICORE_CLIENT_ID }}
      AICORE_CLIENT_SECRET: ${{ secrets.AICORE_CLIENT_SECRET }}
      AICORE_RESOURCE_GROUP: ${{ secrets.AICORE_RESOURCE_GROUP }}
      AICORE_BASE_URL: ${{ secrets.AICORE_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pandas==2.3.3
          #litellm from GitHub main
          pip install git+https://github.com/BerriAI/litellm.git@main

      - name: Run script
        run: python main.py

      - name: Commit and push results
        run: |
          mkdir -p results
          FILE_NAME="results/test_results_$(date +'%Y-%m-%d').html"
          mv test_results.html $FILE_NAME
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $FILE_NAME
          git commit -m "Add test report for $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin main
