name: Test Script LiteLLM Main

on:
  schedule:
    # 00:30 UTC Monday
    - cron: '30 0 * * 1'
  workflow_dispatch: 

jobs:
  run-and-save:
    runs-on: ubuntu-latest

    env:
      AICORE_AUTH_URL: ${{ secrets.AICORE_AUTH_URL }}
      AICORE_CLIENT_ID: ${{ secrets.AICORE_CLIENT_ID }}
      AICORE_CLIENT_SECRET: ${{ secrets.AICORE_CLIENT_SECRET }}
      AICORE_RESOURCE_GROUP: ${{ secrets.AICORE_RESOURCE_GROUP }}
      AICORE_BASE_URL: ${{ secrets.AICORE_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install pandas==2.3.3
          #litellm from GitHub main
          pip install git+https://github.com/BerriAI/litellm.git@main

      - name: Run script
        run: python main.py

      - name: Prepare report for GitHub Pages
        run: |
          REPORT_DATE=$(date +'%Y-%m-%d')
          mkdir -p site/reports
          mv test_results.html site/reports_main/test_results_${REPORT_DATE}.html

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: false
